# Generated by Django 2.0.5 on 2018-07-02 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='排序权值')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 7, 2, 14, 41, 59, 198082, tzinfo=utc), verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=32, verbose_name='菜单名称')),
                ('parent', models.CharField(max_length=32, verbose_name='所属菜单')),
                ('uuid', models.CharField(max_length=32, verbose_name='UUID')),
                ('type', models.SmallIntegerField(default=1, verbose_name='类型')),
            ],
            options={
                'verbose_name': '菜单类别',
                'verbose_name_plural': '菜单类别',
                'ordering': ['ordering', 'id'],
            },
        ),
    ]
