# Generated by Django 2.0.5 on 2018-07-06 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0002_auto_20180706_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemenu',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
    ]
