# Generated by Django 2.0.5 on 2018-07-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0003_auto_20180706_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemenu',
            name='level',
            field=models.SmallIntegerField(default=1, verbose_name='级别'),
        ),
    ]
