# Generated by Django 2.0.5 on 2018-07-09 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0005_auto_20180708_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='排序权值')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=16, verbose_name='标题')),
                ('auther', models.CharField(max_length=16, verbose_name='作者')),
                ('content', models.TextField(verbose_name='内容')),
                ('times', models.SmallIntegerField(verbose_name='浏览次数')),
                ('articlemenu', models.CharField(max_length=32, verbose_name='所属菜单的GUID')),
            ],
            options={
                'ordering': ['-ordering', '-id'],
                'abstract': False,
            },
        ),
    ]
