# Generated by Django 2.0.5 on 2018-07-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0006_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['ordering', 'id'], 'verbose_name': '菜单类别', 'verbose_name_plural': '菜单类别'},
        ),
    ]
