# Generated by Django 2.0.5 on 2018-07-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0007_auto_20180709_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['ordering', 'id'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
