# Generated by Django 2.0.5 on 2018-07-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0008_auto_20180713_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='guid',
            field=models.CharField(default=1, max_length=32, verbose_name='GUID'),
            preserve_default=False,
        ),
    ]
