# Generated by Django 2.0.5 on 2018-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0009_article_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(default=1, verbose_name='摘要'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.CharField(default=1, max_length=256, verbose_name='封面img对应url'),
            preserve_default=False,
        ),
    ]
