# Generated by Django 2.0.5 on 2018-08-07 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0011_auto_20180730_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='排序权值')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('updated', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=32, verbose_name='菜单名称')),
                ('parent', models.CharField(max_length=32, verbose_name='所属菜单')),
                ('guid', models.CharField(max_length=32, verbose_name='GUID')),
                ('level', models.SmallIntegerField(default=1, verbose_name='级别')),
            ],
            options={
                'verbose_name': '菜单类别',
                'verbose_name_plural': '菜单类别',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ArticleMenu',
        ),
    ]
