# Generated by Django 2.0.5 on 2018-08-07 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0012_auto_20180807_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 8, 7, 15, 32, 0, 766000), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='articleclassify',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='articleclassify',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 8, 7, 15, 32, 0, 766000), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='articleclassify',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
