# Generated by Django 2.0.5 on 2018-08-07 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0013_auto_20180807_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auther',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 8, 7, 23, 27, 39, 336714), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='articleclassify',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 8, 7, 23, 27, 39, 336714), verbose_name='创建日期'),
        ),
    ]
