# Generated by Django 2.0.5 on 2018-08-09 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0014_auto_20180807_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleclassify',
            options={'ordering': ['ordering', 'id'], 'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='articleclassify',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='articleclassify',
            name='name',
            field=models.CharField(max_length=32, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='articleclassify',
            name='parent',
            field=models.CharField(max_length=32, verbose_name='所属分类'),
        ),
    ]
