# Generated by Django 2.0.5 on 2018-08-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0015_auto_20180809_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='articlemenu',
        ),
        migrations.AddField(
            model_name='article',
            name='articleclassify',
            field=models.CharField(default=1, max_length=32, verbose_name='所属分类 的GUID'),
            preserve_default=False,
        ),
    ]
