# Generated by Django 2.0.5 on 2018-05-23 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='排序权值')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('money', models.CharField(max_length=64, verbose_name='金额')),
                ('date', models.DateField(default=datetime.datetime(2018, 5, 23, 19, 16, 44, 635475), verbose_name='日期')),
            ],
            options={
                'verbose_name': '金额统计',
                'verbose_name_plural': '金额统计',
                'ordering': ['ordering', 'id'],
            },
        ),
    ]
