# Generated by Django 2.0.5 on 2018-07-02 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneystats',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 2, 22, 35, 20, 183645), verbose_name='日期'),
        ),
    ]
