# Generated by Django 2.0.5 on 2018-07-02 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20180702_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneystats',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 2, 22, 41, 59, 200082), verbose_name='日期'),
        ),
    ]
