# Generated by Django 2.0.5 on 2018-07-06 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20180702_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneystats',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 6, 10, 45, 27, 414038), verbose_name='日期'),
        ),
    ]
