# Generated by Django 2.0.5 on 2018-08-21 09:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='排序权值')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='权限名')),
                ('permissions', models.TextField(editable=False, verbose_name='权限列表')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='排序权值')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='角色名')),
                ('power', models.ManyToManyField(to='user.Power')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='排序权值')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户名')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户姓')),
                ('name', models.CharField(blank=True, db_index=True, max_length=192, null=True, verbose_name='姓名')),
                ('code', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='编号')),
                ('email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='邮件')),
                ('username', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='登录帐号')),
                ('password', models.CharField(max_length=32, verbose_name='加密密码')),
                ('icon', models.CharField(blank=True, max_length=128, null=True, verbose_name='头像')),
                ('level', models.SmallIntegerField(default=1, verbose_name='等级')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='排序权值')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='组名')),
                ('power', models.ManyToManyField(to='user.Power')),
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_user_related', to='user.UserGroup', verbose_name='用户组'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_user_related', to='user.Role', verbose_name='角色'),
        ),
    ]
